services:

  db:
      container_name: postgres-sql
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: demo_db
      ports:
        - "5432:5432"
      volumes:
        - postgres:/var/lib/postgres/data
      networks:
        - spring-network

  spring-boot-app:
    container_name: springdockerdemo
    image: dockerdemo:1.0
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - db

volumes:
    postgres:

networks:
  spring-network:
    driver: bridge
